import {styleTags, tags as t} from "@lezer/highlight"

export const stepcodeHighlight = styleTags({
  "get set async static": t.modifier,
  "para finpara mientras finmientras mientrasque hastaque hasta hacer si sino entonces segun romper continuar repetir proceso finproceso algoritmo finsi finsegun funcion finfuncion subproceso finsubproceso": t.controlKeyword,
  WithStep: t.controlKeyword,
  "definir como dimension": t.definitionKeyword,
  "escribir leer retornar continuar romper": t.keyword,
  ProgramName: t.definition(t.className),
  TemplateString: t.special(t.string),
  BooleanLiteral: t.bool,
  VariableName: t.variableName,
  "CallExpression/VariableName TaggedTemplateExpression/VariableName": t.function(t.variableName),
  Label: t.labelName,
  PropertyName: t.propertyName,
  PrivatePropertyName: t.special(t.propertyName),
  "CallExpression/MemberExpression/PropertyName": t.function(t.propertyName),
  "FunctionName ProcedureName": t.function(t.definition(t.variableName)),
  "VariableDefinition": t.definition(t.className),
  "Comment": t.lineComment,
  Number: t.number,
  String: t.string,
  term: t.keyword,
  ArithOp: t.arithmeticOperator,
  LogicOp: t.logicOperator,
  CompareOp: t.compareOperator,
  "←": t.definitionOperator,
  ":": t.punctuation,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ", ;": t.separator,
  TypeName: t.typeName,
  'entero real cadena caracter logico': t.typeName,
  TypeDefinition: t.definition(t.typeName),
  DefaultLabel: t.controlKeyword,
  "ParameterPass ByReference ByValue": t.modifier,
})